In [5]:
import array as arr
#creating array with intger type
a=arr.array('i',[1,2,3])
print(a)

array('i', [1, 2, 3])


In [6]:
#creating array with float
b=arr.array('d',[1.2,3,4.2])

print(b)

array('d', [1.2, 3.0, 4.2])


In [7]:
import numpy as np

a=np.array([1,2,3,4,5])
a


array([1, 2, 3, 4, 5])

In [8]:
b=np.array([1,2,3.9,4,5.1])
b

array([1. , 2. , 3.9, 4. , 5.1])

In [9]:
c=np.array([1,2,3,5] ,dtype='float')
c

array([1., 2., 3., 5.])

In [10]:
#nested list in multidimensional array
np.array([range(i,i+3)for i in [2,3,4]])


array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [12]:
a=[]
n=int(input("Enter the size of array ="))
for i in range(n):
    val=int(input("enter the number ="))
    a.append(val)

myarray=np.array(a)
myarray

Enter the size of array = 5
enter the number = 1
enter the number = 2
enter the number = 3
enter the number = 4
enter the number = 5


array([1, 2, 3, 4, 5])

In [13]:
#two dimensional array
a=[[1,2,3],[4,5,6],[7,8,9]]
myarray=np.array(a)
print(myarray)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
array1=np.array([[1,2,3],[10,11,12],[5,6,7]])
print(array1)

[[ 1  2  3]
 [10 11 12]
 [ 5  6  7]]


In [14]:
myarray=np.array([[10,11,12],[14,15,16],[17,18,19]])
print(myarray)
print("Dimension of array=",myarray.ndim)
print("Shape of array=",myarray.shape)

[[10 11 12]
 [14 15 16]
 [17 18 19]]
Dimension of array= 2
Shape of array= (3, 3)


In [15]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.zeros((2,3),dtype='float')

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(10,dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
np.ones((3,3),dtype='float')

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [20]:
np.empty([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [22]:
np.linspace(1,100,5,endpoint=False)

array([ 1. , 20.8, 40.6, 60.4, 80.2])

In [23]:
result = np.linspace(1, 100, 5, endpoint=False, dtype=int)
print(result)

[ 1 20 40 60 80]


In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [26]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [27]:
np.full((3,4),3.14161)

array([[3.14161, 3.14161, 3.14161, 3.14161],
       [3.14161, 3.14161, 3.14161, 3.14161],
       [3.14161, 3.14161, 3.14161, 3.14161]])

In [28]:
a=np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [29]:
np.random.randint(0,10,(3,3))

array([[3, 6, 5],
       [7, 5, 4],
       [5, 1, 1]])

In [30]:
np.random.random((3,3))

array([[0.23700776, 0.70124841, 0.51005907],
       [0.62564797, 0.24017478, 0.16070348],
       [0.39303709, 0.71998812, 0.10992174]])

In [31]:
np.random.normal(0,1,(3,3))

array([[-0.09862306, -0.09826741, -2.50913761],
       [-0.5394509 ,  1.15803049,  0.32097469],
       [ 2.15084643,  1.55303311,  0.91297627]])

In [32]:
a=np.random.randint(1,50,12)
a

array([46, 14,  5,  3,  9, 19, 35, 48, 33, 16, 42, 22])

In [33]:
x1=np.random.randint(10, size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,3,3))



In [34]:
print("x3.ndim=",x3.ndim)
print("x3.shape=",x3.shape)
print("x3.size=",x3.size)

x3.ndim= 3
x3.shape= (3, 3, 3)
x3.size= 27


In [35]:
print("dtype=",x3.dtype)

dtype= int32


In [36]:
print("itemsize=",x3.itemsize,"bytes")
print("nbytes=",x3.nbytes,"bytes")

itemsize= 4 bytes
nbytes= 108 bytes


In [37]:
x1=np.random.randint(10, size=6)

print(x1)

[7 9 3 0 3 1]


In [40]:
#indexing
x1[0]

7

In [42]:
import numpy as np

a = []
size = int(input("Array Size: "))

for i in range(size):
    val = int(input("Enter Numbers: "))
    a.append(val)
print("List =", a)

myarray = np.array(a)
print("Numpy Array =", end=" ")
for i in range(myarray.size):
    print(myarray[i], end=" ")

sum = 0
for i in range(myarray.size):
    sum += myarray[i]
print("\nSum of elements =", sum)


Array Size:  5
Enter Numbers:  2
Enter Numbers:  10
Enter Numbers:  1
Enter Numbers:  7
Enter Numbers:  9


List = [2, 10, 1, 7, 9]
Numpy Array = 2 10 1 7 9 
Sum of elements = 29


In [45]:
#array slicing 
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
x[0:5]

array([0, 1, 2, 3, 4])

In [47]:
x[:5]

array([0, 1, 2, 3, 4])

In [48]:
x[5:]

array([5, 6, 7, 8, 9])

In [49]:
x[5:8]

array([5, 6, 7])

In [50]:
x[::2]

array([0, 2, 4, 6, 8])

In [51]:
x[1::]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [53]:
x[5::-1]

array([5, 4, 3, 2, 1, 0])

In [55]:
#multidimensional array slicing
x=np.random.randint(0,10,(3,3))
print(x)

[[9 0 4]
 [8 9 7]
 [0 5 8]]


In [56]:
x[:2,:3]

array([[9, 0, 4],
       [8, 9, 7]])

In [57]:
x[:3,:2]

array([[9, 0],
       [8, 9],
       [0, 5]])

In [58]:
x[::-1,::-1]

array([[8, 5, 0],
       [7, 9, 8],
       [4, 0, 9]])

In [59]:
x[:,0]

array([9, 8, 0])

In [60]:
x[0,:]

array([9, 0, 4])

In [61]:
np.random.seed(111)
a = np.random.randint(1, 500, 30).reshape(6, 5)
a

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [62]:
a[2:]

array([[297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [64]:
a[2:,2:]

array([[442,   8, 269],
       [369, 217, 285],
       [ 22,  55, 201],
       [231, 187, 269]])

In [65]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
x=np.array([1,2,3])
x.reshape(1,3)

array([[1, 2, 3]])

In [68]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [71]:
#reshapiang 

a=np.random.randint(1,50,12)
print("array :",a)
b=a.reshape(3,4)
print("after reshaping 1D to 2D",b)

array : [12 40 25 40 42 15 29  7 31 46 31 30]
after reshaping 1D to 2D [[12 40 25 40]
 [42 15 29  7]
 [31 46 31 30]]


In [73]:
#concating array 

x1=np.array([1,2,3])
x2=np.array([3,2,1])
np.concatenate([x1,x2])

array([1, 2, 3, 3, 2, 1])

In [75]:
grid=np.array([[1,2,3],[4,5,6]])

In [76]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [77]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [80]:
np.concatenate([grid,grid],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [83]:
#stack
x=np.array([1,2,3])
y=np.array([[9,8,7],[6,5,4]])
np.vstack([x,y])


array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [84]:
#splitting array

x=[1,2,3,99,98,3,2,1]
x1,x2,x3=np.split(x,[3,5])

print(x1)
print(x2)
print(x3)

[1 2 3]
[99 98]
[3 2 1]


In [88]:
grid=np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
up,down=np.vsplit(grid,[2])

In [92]:
print(up)

[[0 1 2 3]
 [4 5 6 7]]


In [93]:
print(down)

[[ 8  9 10 11]
 [12 13 14 15]]
