In [1]:
import numpy as np

In [10]:
a=np.array([1,2,3])
print(type(a))


<class 'numpy.ndarray'>


In [8]:
a=np.array(1,2,3)
print(type(a))

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [12]:
print(a)

[1 2 3]


In [16]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [27]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [38]:
np.arange(1,21).reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [42]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.random.random(5,2)

TypeError: random() takes at most 1 positional argument (2 given)

In [50]:
np.random.random((5,4))

array([[0.7751395 , 0.97690161, 0.44303389, 0.15120888],
       [0.39038647, 0.64594534, 0.9863197 , 0.05293421],
       [0.25529518, 0.74832927, 0.15256363, 0.85932729],
       [0.41121015, 0.96323593, 0.73560919, 0.16452393],
       [0.02436108, 0.25388078, 0.51097183, 0.80877103]])

In [52]:
np.linspace(-10,10,6)

array([-10.,  -6.,  -2.,   2.,   6.,  10.])

In [54]:
np.identity(3,3)

TypeError: Cannot interpret '3' as a data type

In [56]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
a1=np.arange(1,10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)



print(a1)
print("--------------")
print(a2)
print("--------------")
print(a3)


[1 2 3 4 5 6 7 8 9]
--------------
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
--------------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [66]:
#ndim ----dimension check
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [68]:
#shape 

print(a1.shape)
print(a2.shape)
print(a3.shape)

(9,)
(3, 4)
(2, 2, 2)


In [70]:
#itemsize --- show storage take
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [74]:
#dtype--- datatype checlk
a1.dtype

dtype('int32')

In [87]:


a1=np.arange(0,12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [89]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])